// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAfZGwvAfQiJsMWwi2XPLD4_s_9nkKuI',
    appId: '1:411033502161:web:a945d919fe898ee89760f0',
    messagingSenderId: '411033502161',
    projectId: 'e-posyandu-d5ae6',
    authDomain: 'e-posyandu-d5ae6.firebaseapp.com',
    storageBucket: 'e-posyandu-d5ae6.appspot.com',
    measurementId: 'G-3WGRQ7K7TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbe9UMC0SijHUjfHiYiNbXjXF6be8yM9k',
    appId: '1:411033502161:android:e3d9aa50b8d823e59760f0',
    messagingSenderId: '411033502161',
    projectId: 'e-posyandu-d5ae6',
    storageBucket: 'e-posyandu-d5ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWPECuL1rdnjYlLwoNF4ku-nW_89yIkQw',
    appId: '1:411033502161:ios:90add5b36264e0409760f0',
    messagingSenderId: '411033502161',
    projectId: 'e-posyandu-d5ae6',
    storageBucket: 'e-posyandu-d5ae6.appspot.com',
    iosClientId: '411033502161-jgivh88lclervsggm6hjbvtlkabgmk3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePosyandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWPECuL1rdnjYlLwoNF4ku-nW_89yIkQw',
    appId: '1:411033502161:ios:90add5b36264e0409760f0',
    messagingSenderId: '411033502161',
    projectId: 'e-posyandu-d5ae6',
    storageBucket: 'e-posyandu-d5ae6.appspot.com',
    iosClientId: '411033502161-jgivh88lclervsggm6hjbvtlkabgmk3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePosyandu',
  );
}
